### PR TITLE
Feat enable auto update

### LINKED ISSUE #701: Enable auto updates
Todo: 

- [x] Update release repo in `package.json`: https://github.com/maidsafe/safe_browser/pull/702/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R183
- [x] Check out adding a menu option for this! https://github.com/electron-userland/electron-builder/blob/docs/encapsulated%20manual%20update%20via%20menu.js
- [x] Ensure auto update is not triggered in dev mode

### PR DESCRIPTION
**Pull request by joshuef**
Fixes #701 

QA: We'll have to validate the whole process. Including now triggering builds w/signed packages. 

Dlding that package to a platform, and then spurring another update...

### CODE REVIEW

**Comment by hunterlester** [comment]
@joshuef @S-Coyle I was able to package and publish to my releases: https://github.com/hunterlester/safe_browser/releases/tag/v0.13.0
Was the issue that this was not happening?

**Comment by S-Coyle** [comment]
@hunter the issue was that the packaged files then didn't work on Windows
or Linux, macOS was fine

**Comment by hunterlester** [comment]
PR for this branch: https://github.com/joshuef/safe_browser/pull/17

**Comment by joshuef** [comment]
@hunterlester can you rebase your PR please 🙇 .

**Comment by hunterlester** [comment]
@joshuef rebased just now

**Comment by joshuef** [comment]
@hunterlester the branch target of that PR was off (was targetting `dev`), but I've pulled in the commits to this branch for this PR now.

**Pull request closed without merging**
