### PR TITLE
feat(Travis + Tabbar): Replace react-icons with antD icons in TabBar/. Update Travis for windows

### LINKED ISSUE #397: Migrate from AppVeyor to Travis
https://blog.travis-ci.com/2018-10-11-windows-early-release

### PR DESCRIPTION
**Pull request by shriram2301**
resolves #397 
resolves #455

### CODE REVIEW

**Comment by joshuef** [comment]
@shriram2301 I'm confused. Is this PR now replacing (https://github.com/maidsafe/safe_browser/pull/449) ? For getting widows in travis?

If so can you update the naming of this / close the other, please.

And then let's also remove `appveyor.yml` from this branch. 

Cheers!

**Comment by joshuef** [comment]
@shriram2301 have you posted to the travis windows forum about the windows issue?

Can you link me please.

**Comment by shriram2301** [comment]
> @shriram2301 have you posted to the travis windows forum about the windows issue?
> 
> Can you link me please.

https://travis-ci.community/t/yarn-run-build-failure-in-windows-when-node-env-set-to-dev/1588 

this is the link to the issue I raised in Travis forum

**Comment by shriram2301** [comment]
Options I have tried so far to get `yarn run build` working 
- yarn run build
- yarn build
- travis_retry eval "yarn run build"
- travis_retry eval "yarn build"
- travis_wait travis_retry eval "yarn build"
- travis_wait travis_retry eval "yarn run build"
- travis_wait yarn build
- travis_wait yarn run build
- travis_retry yarn build
- travis_retry yarn run build

**Comment by shriram2301** [comment]
> As per [yarnpkg/yarn#5055](https://github.com/yarnpkg/yarn/issues/5055) have you tried running yarn `verbose` @shriram2301 ?

Tried doing this by running `yarn run build --verbose` it still doesn't work for `windows dev` for reference please see https://travis-ci.org/maidsafe/safe_browser/jobs/477366449

**Comment by joshuef** [comment]
Closing as this as been usurped by other windows test branches

**Pull request closed without merging**
