### PR TITLE
fix(auth): proper values returned on auth_decode_ipc_msg errors

### LINKED ISSUE #454: Automatically reject authorisation request which mockbit doesn't match
For the scenarios when the browser is running for mock network, and an application sends an authorisation request which is for live network (or the other way around), the authenticator should be rejecting the authorisation automatically and sending such a response to the application. Currently the application doesn't receive any type of response.

### PR DESCRIPTION
**Pull request by hunterlester**
- Test case for authenticator error -208 IncompatibleMockStatus
  - Test case for authenticator error -103 when decoding share MData
    request for non-existent MData

Resolves #452 
Resolves #454 

@joshuef @bochaco I'm unable to properly test 2 new cases, see [auth.spec](https://github.com/maidsafe/safe_browser/pull/554/files#diff-a003f29f7e2f9aeecfe6e3fbb39e3d2e), because they both output a `-1 ERR_ENCODE_DECODE_ERROR`. I need to think about what I need to do to properly include these tests.
Also, I've decided to simply show an error notification in browser. I don't think there is an easy way to respond to an external app with an error. The errors occur when attempting to decode the auth requests and decoding is needed to be able to then encode a response. I'll continue to think about a solution.

QA:
Easiest way to test this PR would be to:
- Run API playground
- Initialise app
- Pass object to `authorise` operation and run, where the whole func to be executed as auth should look like: 
```
async () => {
  
        const authReqUri = {
          uri: 'safe-auth:bAAAAAAEKDQ7DAAAAAAACOAAAAAAAAAAANZSXILTNMFUWI43BMZSS4YLQNFPXA3DBPFTXE33VNZSC453FMJRWY2LFNZ2C4OIAC4AAAAAAAAAAAU2BIZCSA53FMIQECUCJEBYGYYLZM5ZG65LOMQGQAAAAAAAAAACNMFUWIU3BMZSSATDUMQXACAQAAAAAAAAAAADQAAAAAAAAAAC7OB2WE3DJMMCAAAAAAAAAAAAAAAAAAAIAAAAAEAAAAABQAAAABQAAAAAAAAAAAX3QOVRGY2LDJZQW2ZLTAQAAAAAAAAAAAAAAAAAACAAAAABAAAAAAMAAAAAA'
      };
  
      // Sends autorisation request to authenticator
      try {
        authUri = await safe.authorise(authReqUri);
      } catch (err) {
        return err;
      }
      return `Auth URI returned. Next, back in auth section, pass authUri to loginFromUri.`;
    }
```
- Expect to see an error notification
- Same steps for [encodedNonExistentShareMDataReq](https://github.com/maidsafe/safe_browser/compare/master...hunterlester:454?expand=1#diff-a003f29f7e2f9aeecfe6e3fbb39e3d2eR28)

To QA with external app:
- You could use my repo and [set `forceUseMock` to `false` here](https://github.com/hunterlester/safe-app-base/blob/master/renderer.js#L58), in order to get a `-208` error.
- To test for error `-103`, uncomment [this block](https://github.com/hunterlester/safe-app-base/blob/master/renderer.js#L60-L68), then replace [authUri here](https://github.com/hunterlester/safe-app-base/blob/master/renderer.js#L69), with the `shareMDataReqUri` variable.

### CODE REVIEW

**Comment by joshuef** [comment]
> The errors occur when attempting to decode the auth requests and decoding is needed to be able to then encode a response. I'll continue to think about a solution.

Hmm, yeh given that situation, it seems like a notification is the best thing we can do 👍

**Comment by hunterlester** [comment]
I've taken note of this [TODO](https://github.com/maidsafe/safe_browser/blob/5b52869465a4174674865e591b023af30a51f1b2/app/extensions/safe/test/auth/auth.spec.js#L410), however I do think it should be for a separate task as it effects code in Authenticator web app which requires some extra testing to prevent regression.

**Comment by joshuef** [comment]
Hmm. @hunterlester following your instructions I don't see any notification pop up :( on OSX. Will check on linux now

**Comment by joshuef** [comment]
I'm only seeing https://www.dropbox.com/s/d9ds89pafxqpb4w/Screenshot%202019-02-19%2012.00.39.jpg?dl=0 on both osx/linux, FYI @hunterlester

**Comment by hunterlester** [comment]
@joshuef Ah, I gave bad instructions.
The following object should be passed to `authorise`:
```
const authReqUri = {
    uri: 'safe-auth:bAAAAAAEKDQ7DAAAAAAACOAAAAAAAAAAANZSXILTNMFUWI43BMZSS4YLQNFPXA3DBPFTXE33VNZSC453FMJRWY2LFNZ2C4OIAC4AAAAAAAAAAAU2BIZCSA53FMIQECUCJEBYGYYLZM5ZG65LOMQGQAAAAAAAAAACNMFUWIU3BMZSSATDUMQXACAQAAAAAAAAAAADQAAAAAAAAAAC7OB2WE3DJMMCAAAAAAAAAAAAAAAAAAAIAAAAAEAAAAABQAAAABQAAAAAAAAAAAX3QOVRGY2LDJZQW2ZLTAQAAAAAAAAAAAAAAAAAACAAAAABAAAAAAMAAAAAA'
};
```

**Comment by joshuef** [comment]
aha, right. I'll update the original comment to include full code for this.

Looking good now on osx

**Comment by joshuef** [comment]
This has been placed atop the #598, so merging that PR will close this one. (And that ideally will form initial commit after next release)

**Comment by joshuef** [comment]
merged in with #598

**Comment by safesurfer** [comment]
Tested with live browser and mock application which @hunterlester suggested, and getting the error `-208 IncompatibleMockStatus` while authorising, as expected. - first scenario
Tested the live app with live browser after uncommenting the block and replacing auth uri with `shareMDataReqUri `, which hunter mentioned, it throws `-103 error` as expected - second scenario

**Pull request closed without merging**
