### PR TITLE
chore(CI): updates AppVeyor and Travis CI to pull file resources

### PR DESCRIPTION
**Pull request by hunterlester**
@joshuef PR updated to include AppVeyor config.
Published released based on tag push: https://github.com/hunterlester/safe_browser/releases/tag/peruse2

### CODE REVIEW

**Comment by hunterlester** [comment]
@bochaco Still investigating why Github credentials are working on AppVeyor but not on Travis for pulling for `release_config`. This was put on pause to address other tasks.

**Comment by hunterlester** [comment]
When building on my fork of `safe_browser` in AppVeyor, the Github credentials used to pull from the [release_config](https://github.com/maidsafe/release_config) repository are successful.
However when building from this repository in AppVeyor, `Invoke-WebRequest` returns `401 Unauthorized`.
I need help understanding why this is the case.
Same exact `access_token` being used.

**Comment by hunterlester** [comment]
Resolves #440

**Comment by hunterlester** [comment]
I'll resume work on this once #397 is complete, which involves deprecating the use of so-called secure environment variables in Travis.

**Comment by joshuef** [comment]
just to be clear, this _isnt_ ready for review then @hunterlester ? If that's true can you update the col in the project please. 

If it is ready... What are we calling success here? I'm not sure what to be checking for.

**Pull request closed without merging**
