### PR TITLE
MAID-2321 fix/The readConfig function was creating an additional an unnecessary connection

### PR DESCRIPTION
**Pull request by bochaco**

### CODE REVIEW

**Comment by theWebalyst** [comment]
Is this likely to be related to the following, or not so much given that I'm getting it every time even on a clean machine and first use of the browser? Or actually, could you try it with your build, just go to safe://myfd.rsports, then click on blue cube top right - thanks! 

https://github.com/maidsafe/safe_browser/issues/162

**Comment by bochaco** [comment]
This is not the only PR related to MAID-2321, there was another PR merged some days ago which also helping to solve MAID-2321. We are testing now to see if there are more enhancements to be made. We are in fact using your safe site to test.

**Comment by theWebalyst** [comment]
Cool! If you get anything that runs my site please let me know as I'd love to get hold of it ASAP :-)

**Comment by bochaco** [comment]
You can give it a try with the latest code from browser's master branch. I just tried it on Linux and I'm able to connect with it, it throws an error which is not related to the SAFE API or network though.

**Comment by theWebalyst** [comment]
@bochachao - I had a problem with the build - are you sure master is ok? It builds but gives an error on 'yarn start'. I'm on riot.im if you have a moment.

**Comment by theWebalyst** [comment]
**Update:** I get further after 'yarn package' and running the linux-distribution binary. No unusual errors on start, nothing unexpected in the linux console, but on trying to login I'm getting ```Core error: Unexpected: Could not connect to the SAFE Network``` although my IP is correct.

**Comment by theWebalyst** [comment]
**Update:** I get further after 'yarn package' and running the linux-distribution binary. No unusual errors on start, nothing unexpected in the linux console, but on trying to login I'm getting ```Core error: Unexpected: Could not connect to the SAFE Network``` although my IP is correct.

**Pull request merged**
