### PR TITLE
Experimental API toggle

### PR DESCRIPTION
**Pull request by joshuef**

### CODE REVIEW

**Comment by joshuef** [comment]
To keep track:

- [] WebID Dropdown currently doesnt appear to change upon auth.
- [] E2e tests not having a good time.

**Comment by hunterlester** [comment]
@joshuef I pushed a commit to fix web ID dropdown: https://github.com/hunterlester/safe_browser/tree/FixWebIdDropdown

**Comment by hunterlester** [comment]
@joshuef Here's a branch for styles: https://github.com/hunterlester/safe_browser/tree/WarnOnExperimentalApis-Styles

**Comment by joshuef** [comment]
Those styles are included now @hunterlester 👍

**Comment by hunterlester** [comment]
https://github.com/hunterlester/safe_browser/tree/SpectronArea

**Comment by hunterlester** [comment]
@joshuef Fix for call stack error: https://github.com/hunterlester/safe_browser/tree/RangeError

**Comment by joshuef** [comment]
For #415

**Pull request merged**
