### PR TITLE
[WIP] fix(reconnect): stabilises reconnection and reloading handling

### LINKED ISSUE #457: Problems with 'Reconnect Now'
This issue seems similar to PR #319, however there are some differences
- as mentioned in 319, it works with auth page, but it shows `Unable to navigate to site. Will automatically reload when network is connected...` message when I open a new tab to access a webpage.
- the new issue is intermittent and this also happens when I click `reconnect now`
- this time the reconnecting spinner spins infinitely
- and the browser becomes unresponsive, such as logout button doesn't work, unable to switch tabs, needs about 5 clicks to switch next tab. STR: try opening new tab and try to access some link, while it is loading click auth page tab

Note: I got this issue on Windows with prod version

### PR DESCRIPTION
**Pull request by hunterlester**
Resolves #457 

  - Fixed: Upon network disconnect, automated reconnect attempts are more
    stable
  - Added: Reconnect countdown UI
  - Added: On disconnect notification, user is given button to manually reconnect
  - Added: Test spec for new Notifier extension
  - Changed: Removes close tab/add tab behavior when load fails due to
    network disconnect. Replaced with reload behavior solely when network reconnects.

For QA:
Instead of waiting 2 minutes for network connection to be dropped upon simulating network disconnect, I switch from Ethernet connection to WIFI, which instantaneously triggers a network disconnect in the browser.

### CODE REVIEW

**Comment by joshuef** [comment]
> Added: Reconnect key binding: CommandOrCtrl + ALT + R

I'm not sure we need this TBH. I mean... ideally you shouldn't be disconnected _soooo_ often that it's needed, right?

**Comment by joshuef** [comment]
I'm still seeing some odd behaviour on OSX, lets have a HO and look at this later on today 👍 

eg: 

https://www.dropbox.com/s/d5gf7172igg7ku7/Screenshot%202019-01-03%2014.28.00.jpg?dl=0

**Comment by joshuef** [comment]
@hunterlester just a follow up to the wee HO.

https://github.com/maidsafe/safe_browser/pull/477/files#diff-c1373fedfea725334ffc2413bc67f357L26

Here, we've lost auto reconnect (as the PR stands), which I think we need.

But it looks like how we had this set up was ripe for being hammered by reconnect calls which could have caused the bugginess we saw.

So we should try:

- [ ] Create a variable to track if a `timerIsRunning`, so a second call doesn't create a new timer when one is already running.
- [ ] Perhaps distinguish the timer from a manual click of the `attempt reconnect` button?
- [ ] Clear the timer once connection has been successfully established (and clear `timerIsRunning`also)

**Comment by joshuef** [comment]
@hunterlester So this is now triggering reload when reconnected, which works for attempting to access a tab once it's known its disconnected.

BUT:

If i disconnect, then attempt to access a site (before the browser notes it's disconnected), the error page shows only `OK`. The reconnect notifier shows up, and reenabling connection, it _appears_ to be reloading (loading icon shows), however the page/correct error (no content found), is not shown. The page is blank.

All works as expected when attempting to open a tab once the browser is aware of being disconnected (correct error is shown, page reloads properly).

ALSO:

I noted, when disconnecting/reconnecting / clicking the button to reconnec tthat the countdown value started jumping around(eg: 10..4..8..12). So it seems that there are still _many_ counters running, each updating the state on the countdown shown to the user.

Last thing to note for now: Can you see if there's a nicer / cleaner way to present the reconnection indicator (or maybe we just remove the blue loading indicator etc... blue on red is a bit gross. (And maybe... does it need to be a red error notification, maybe info one suffices? (though im no sure that affects the colour situation there: P )

**Comment by hunterlester** [comment]
- > If i disconnect, then attempt to access a site (before the browser notes it's disconnected), the error page shows only OK. The reconnect notifier shows up, and reenabling connection, it appears to be reloading (loading icon shows), however the page/correct error (no content found), is not shown. The page is blank.

    I'm working on reproducing this. Unable to thus far.

- Counter and loading presentation cleaned up. Instead of `error`, the notifier is an `info`, so looks a bit better for now until we switch over to `antd`.

- > (Should the notification be dismissible?)

    It's currently a default button, which I can change but I think it should be scoped for another task, since making it opt-in will affect other `addNotification` calls.

- > Perhaps const isDisconnected = state === SAFE.NETWORK_STATE.DISCONNECTED; needs to check if this is a fresh disconnect? Or one previously seen / notified / acted upon?
    
    As far as I can tell a 'Disconnect' network state event is only passed once when the network connection is dropped. Do you mean a subsequent `Disconnect` event after having reconnected and receiving a `Connected` network state event?

**Comment by joshuef** [comment]
>  Do you mean a subsequent Disconnect event after having reconnected and receiving a Connected network state event?

Could be. Not sure why twas jumping around so. Will have a try w/ latest code and see what i can see

**Comment by joshuef** [comment]
Info / button is looking okay yep!

I'm not seeing 'ok' anymore, nor the jumping counter 👍 

I am seeing that a window load that triggers awareness of disconnection still doesn't reload properly upon connection though.

**Comment by hunterlester** [comment]
Able to reliably simulate network disconnect on Windows using Defender Firewall to create an outbound rule just for SAFE Browser.
Still unable to reproduce blank pages though @joshuef as well as that BG crash which occurs upon clicking `Reconnect` manually.
Need to dig deeper. Looking for a memory profiler that I can use to watch Electron's processes and what exactly is happening when 1. bg crash occurs and 2. when `webview` goes blank upon reconnect.

**Comment by hunterlester** [comment]
@joshuef Got my hands on a Mac for testing purposes. Reproducing what you observed.
There are two primary issues:
1. When loading a site just before network disconnect is observed, then opening a blank tab, the loading tab triggers a `did-fail-load` webview event. Not able to reproduce this on Windows. This is an easy problem as I have to consider that either `webFetch` can error or Chromium webview can error, so I just have to handle both of those cases. Leading to the next problem.
2. I'm able to handle both Chromium and `webFetch` errors however and I'll observe a tab begin to reload as expected, HOWEVER, if that tab is not currently active, then the page will render blank, if it is active it will render the page as expected. That's where I'm leaving off for the day. Stumped on this one.
Does this make sense?
Anyway, I've pushed a commit, if you have any leads about what's going on here.

**Comment by hunterlester** [comment]
Resolves #529

As-is, this PR improves tab behavior and reconnect behavior.
Reconnect edge case on OSX will be resolved upon updating electron to v4.

OSX edge-case:
```
I'm able to handle both Chromium and webFetch errors and observe a tab begin to reload as expected, HOWEVER, if that tab is not currently active, then the page will render blank, if it is active it will render the page as expected. That's where I'm leaving off for the day. Stumped on this one.
```
I'm paranoid now about regressions, so I'll be adding tests to prevent them and subject this PR to critical QA from @calumcraig and @safesurfer

**Comment by hunterlester** [comment]
Blocked by #410

**Comment by hunterlester** [comment]
Closing this PR because browser architecture has and will drastically change since it was originally opened.

**Pull request closed without merging**
